### ISSUE TITLE
Bidirectional communication.

### ISSUE THREAD

**Issue by LePhasme** [MAKIO135/sensorShieldLib#4]
Hi Lionel!

Any plan to make this lib bidirectional? (i.e. receive JSON from the serial port and write the values to their related pin). I may try to do it, but my C is a bit rusty and it could be out of the scope of your lib, don't know...

**Comment by MAKIO135** [comment]
Thought about this but, i believe firmata can be more appropriate.
Or you can try combining with [https://github.com/interactive-matter/aJson](https://github.com/interactive-matter/aJson) or [https://github.com/bblanchon/ArduinoJson](https://github.com/bblanchon/ArduinoJson)
